version: "3.8"

services:
  sentence-alignment-1:
    build: .
    # runtime: nvidia
    ports:
      - "5003:5000"
    volumes:
      - ./:/app
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility
